import type { TutorActivityStage, TutorTextField } from "../lib/tutor-stream-types";

export type TutorActivity = {
  id: string;
  stage: TutorActivityStage;
  state: "active" | "done" | "denied";
};
export type TutorText = Partial<Record<TutorTextField, string>>;
const labels: Record<TutorActivityStage, [string, string]> = {
  search_conversation: ["Looking up an earlier conversation", "Earlier conversation checked"],
  memory: ["Recalling your study memory", "Study memory checked"],
  compaction: ["Summarizing earlier conversation", "Earlier conversation summarized"],
  question: ["Checking the question and your progress", "Question and progress checked"],
  model: ["Waiting for Chiikawa’s response", "Chiikawa’s response received"],
  get_question_context: ["Reading question context", "Question context read"],
  find_related_questions: ["Finding related practice", "Related practice checked"],
  get_revealed_answer: ["Reading the revealed source rationale", "Source rationale read"],
  get_session_learning_context: ["Checking your learning progress", "Learning progress checked"],
};
export function activityLabel(activity: TutorActivity) {
  return activity.state === "denied"
    ? activity.stage === "compaction"
      ? "Earlier conversation could not be summarized; using recent context"
      : "This source was unavailable to Chiikawa"
    : labels[activity.stage][activity.state === "active" ? 0 : 1];
}
export default function TutorResponse({
  text,
  activities,
  streaming,
}: {
  text: TutorText;
  activities: TutorActivity[];
  streaming: boolean;
}) {
  return (
    <div className="tutor-panel" aria-label="Chiikawa’s commentary">
      <p className="eyebrow">Chiikawa’s commentary · {streaming ? "Live response" : "Complete"}</p>
      {activities.length > 0 && (
        <details className="tutor-activity" open={streaming}>
          <summary>Sources and activity</summary>
          <ul>
            {activities.map((activity) => (
              <li key={activity.id}>
                <span aria-hidden="true">
                  {activity.state === "done" ? "✓" : activity.state === "denied" ? "—" : "•"}
                </span>
                {activityLabel(activity)}
              </li>
            ))}
          </ul>
        </details>
      )}
      {text.approach && (
        <div className="tutor-approach">
          <h4>Teaching approach</h4>
          <p>{text.approach}</p>
          <small>A brief teaching plan generated by Chiikawa.</small>
        </div>
      )}
      {text.message && <p className="tutor-message">{text.message}</p>}
      {text.concept && (
        <div className="tutor-detail">
          <strong>Concept</strong>
          <p>{text.concept}</p>
        </div>
      )}
      {text.nextStep && (
        <div className="tutor-detail">
          <strong>Next step</strong>
          <p>{text.nextStep}</p>
        </div>
      )}
    </div>
  );
}
